name: "Azure Machine Learning Workspace Action"
description: "Connect to or create an Azure Machine Learning Workspace with this GitHub Action"
author: "Marvin Buss"
inputs:
  parametersFile:
    description: "JSON file including the parameters of the workspace."
    required: false
    default: "workspace.json"
  subscriptionId:
    description: "ID of the Azure Subscription"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
